# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  build_tool:
    required: true
    default: maven
  build_environment:
    required: true
    default: nonprod
  build_tool_version:
    required: false
  application_name:
    required: true
  build_file_path:
    required: false
    default: .
  build_file_name:
    required: false
  settings_file_path:
    required: false
  settings_file_name:
    required: false
  build_arguments:
    required: false  
  build_phases: 
    required: false
  jdk_version:
    required: false
  node_version: 
    required: false
  build_and_push_container_image:
    required: false
  cr_imagename:
    required: false
  cr_imagetag:
    required: false
  cr_dockerfile_name:
    required: false
  cr_dockerfile_path:
    required: false
  cr_servername:
    required: false
  cr_subscription:
    required: false
  cr_tenant:
    required: false
  cr_username:
    required: false
  cr_password:
    required: false
  artifact_repository_url:
    required: false
  run_code_quality_analysis:
    required: true
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments:
    required: false
  cq_project_name:
    required: false

  run_application_build:
    required: false
  run_library_build:
    required: false
  is_prod_build:
    required: false
    default: false
  run_typecheck_validation:
    required: false
    default: false
  run_schema_validation:
    required: false
    default: false
  run_unit_test:
    required: false
    default: false
    
 
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash  
          
    - name: ========== Build and push Build Artifacts to artifact Store for Maven ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/maven-ci@latest
      with:
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        settings_file_path: ${{ inputs.settings_file_path }}
        settings_file_name: ${{ inputs.settings_file_name }}
        build_phases: ${{ inputs.build_phases}}
        build_arguments: ${{inputs.build_arguments}}
        build_and_push_container_image: ${{inputs.build_and_push_container_image}}
        jdk_version: ${{ inputs.jdk_version }}
        run_code_quality_analysis: ${{ inputs.run_code_quality_analysis }}  
        cq_host_url: ${{ inputs.cq_host_url }} 
        cq_project_key: ${{ inputs.cq_project_key }} 
        cq_project_name: ${{ inputs.cq_project_name }}
        cq_token: ${{ inputs.cq_token }}
        cq_scan_arguments: ${{ inputs.cq_scan_arguments }}
        
      if: ${{ ( inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' ) }}
    
    

    
 #========== Gradle Build CI ==============#
    
    
    - name: ========== Build and push Build Artifacts to artifact Store for Gradle ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/gradle-ci@latest
      with:
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        settings_file_path: ${{ inputs.settings_file_path }}
        settings_file_name: ${{ inputs.settings_file_name }}
        build_phases: ${{ inputs.build_phases}}
        build_arguments: ${{ inputs.build_arguments }}
        jdk_version: ${{ inputs.jdk_version }}
        build_and_push_container_image: ${{inputs.build_and_push_container_image}}
        artifact_repository_pat: ${{ inputs.artifact_repository_pat }}
        run_code_quality_analysis: ${{ inputs.run_code_quality_analysis }}  
        cq_host_url: ${{ inputs.cq_host_url }} 
        cq_project_key: ${{ inputs.cq_project_key }}
        cq_project_name: ${{ inputs.cq_project_name }}
        cq_token: ${{ inputs.cq_token }}
        cq_scan_arguments: ${{ inputs.cq_scan_arguments }}
      if: ${{ ( inputs.build_tool == 'gradle' || inputs.build_tool == 'gradlew' ) }}
    
    
 #========== NodeJS Build CI ==============#   
    
    
    - name: ========== Build and push Build Artifacts to artifact Store  for NodeJS ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/nodejs-npm-ci@latest
      with:
        application_name: ${{inputs.application_name}}
        build_tool_version: ${{ inputs.build_tool_version }}
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        node_version: ${{ inputs.node_version  }}
        build_phases: ${{ inputs.build_phases  }}
        build_and_push_container_image: ${{inputs.build_and_push_container_image}}
        run_code_quality_analysis: false
        artifact_repository_url: ${{inputs.artifact_repository_url}}
      if: ${{  inputs.build_tool == 'npm'  }}
      
    - name: ========== Build and push Build Artifacts to artifact Store  for NodeJS ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/nodejs-yarn-ci@latest
      with:
        application_name: ${{inputs.application_name}}
        build_tool_version: ${{ inputs.build_tool_version }}
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        build_and_push_container_image: ${{inputs.build_and_push_container_image}}
        #node_version: ${{ inputs.node_version  }}
        #build_phases: ${{ inputs.build_phases  }}
        run_code_quality_analysis: false
      if: ${{  inputs.build_tool == 'yarn'  }}   
      
    - name: ========== Build and push Build Artifacts to artifact Store  for NodeJS Yarn-nx==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/nodejs-yarnnx-ci@latest
      with:
        application_name: ${{inputs.application_name}}
        node_version: ${{ inputs.build_tool_version }}
        #node_version: ${{ inputs.node_version }}
        #build_file_path: ${{ inputs.build_file_path }}
        #build_file_name: ${{ inputs.build_file_name }}
        build_and_push_container_image: ${{inputs.build_and_push_container_image}}
        is_application_build: ${{ inputs.run_application_build }}
        is_library_build: ${{ inputs.run_library_build }}
        run_code_quality_analysis: false
      if: ${{  inputs.build_tool == 'yarnnx'  }}   
       
 ##=============================== END OF CI INVOKES  ===================================##
 
 
 ##======================== INVOKE IMAGE BUILD and PUSH to CONTAINER REGISTRY ===================##
    
    - name: =========  Build and push image to Container Registry. ===========
      if: ${{ ( inputs.build_and_push_container_image == 'true'  ) }}
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/push_image@latest
      with:
        cr_dockerfile_name: ${{inputs.cr_dockerfile_name}}
        cr_dockerfile_path: ${{inputs.cr_dockerfile_path}}
        cr_imagename: ${{inputs.cr_imagename}}
        cr_imagetag: ${{inputs.cr_imagetag}}
        cr_username: ${{inputs.cr_username}}
        cr_password: ${{inputs.cr_password}}
        cr_servername: ${{inputs.cr_servername}}
 # below properties is required if  you are using ACR
        cr_tenant: ${{inputs.cr_tenant}}    
        cr_subscription: ${{inputs.cr_subscription}} 
    
    
    
    
    
# ==================================================================================================   
    
    
    
    
    
    
#     - name: Validate Gradle wrapper
#       if: ${{ inputs.build_tool == 'gradle' }}
#       uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      
#     - name: Build with Gradle
#       if: ${{ inputs.build_tool == 'gradle' }}
#       run: ./gradlew build
#       shell: bash
      
        
    
    
#       ############ Test Ignore ##########
      
#     - name: calling another composite action
#       id: foo
#       uses: gopinath-velayudhan-mns/shared_composite_repo/workflows/sample@latest
#       with:
#         who-to-greet: 'Mona the Octocat'
#     - run: echo random-number ${{ steps.foo.outputs.random-number }}
#       shell: bash


############### Maven
#     - run: ls -lart
#       shell: bash
    
#     - name: Maven Build and install Artifacts
#       if: ${{ ( inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' )  && ( contains( inputs.build_phases,'install') || contains(  inputs.build_phases , 'package') )}}
#       run: |
#         mvn clean install ${{inputs.maven_build_arguments}} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
#       shell: bash  
    
#     - name: Unit_Test
#       if: ${{ (inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' ) && contains( inputs.build_phases , 'test' ) }} 
#       run : | 
#         echo Running Unit Test - ${{ inputs.build_phases }}
#         mvn test ${{inputs.maven_build_arguments}} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
#         echo 'Test Phase - completed'
#       shell: bash
      
#     - name: Publish built artifact to Artifact repository
#       if: ${{ (inputs.build_tool == 'maven' || inputs.build_tool == 'mvn') && contains( inputs.build_phases , 'deploy' ) && inputs.settings_file_name }}   
#       run : |
#         echo Executing Phase Deploy - ${{ inputs.build_phases }}
#         mvn deploy -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} ${{inputs.maven_build_arguments}}
#       shell: bash  
      
#     - name: Code Quality Analysis
#       if: ${{ inputs.run_code_analysis == 'true' }}  
#       run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar
#            -Dsonar.projectKey=${{inputs.cq_project_key}} 
#            -Dsonar.host.url=${{inputs.cq_host_url}} 
#            -Dsonar.login=${{inputs.cq_token}} ${{inputs.maven_build_arguments}} 
#            ${{inputs.maven_build_arguments}}
#       shell: bash
