# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  build_tool:
    required: true
    default: maven
  pom_path:
    required: false
    default: .
  pom_file_name:
    required: false
    default: pom.xml
  settings_file_path:
    required: false
  settings_file_name:
    required: false
  maven_build_arguments:
    required: false
    
  build_phases: 
    required: false
    default: 'clean package install '
  
  az_artifact_repository_pat:
    required: false
    
  run_code_analysis:
    required: true
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
 
  
           
  
   
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run: ls -lart
      shell: bash
    
    - name: Maven Build and install Artifacts
      if: ${{ ( inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' )  && ( contains( inputs.build_phases,'install') || contains(  inputs.build_phases , 'package') )}}
      run: |
        mvn clean install ${{inputs.maven_build_arguments}} -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
      shell: bash  
    
    - name: Unit_Test
      if: ${{ (inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' ) && contains( inputs.build_phases , 'test' ) }} 
      run : | 
        echo Running Unit Test - ${{ inputs.build_phases }}
        mvn test ${{inputs.maven_build_arguments}} -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
        echo 'Test Phase - completed'
      shell: bash
      
    - name: Deploy and Publish Artifact
      if: ${{ (inputs.build_tool == 'maven' || inputs.build_tool == 'mvn') && contains( inputs.build_phases , 'deploy' ) && inputs.settings_file_name }}   
      run : |
        echo Executing Phase Deploy - ${{ inputs.build_phases }}
        mvn deploy -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }} -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }} ${{inputs.maven_build_arguments}}
      shell: bash  
      
    - name: Code Quality Analysis
      if: ${{ inputs.run_code_analysis == 'true' }}  
      run: -Dsonar.projectKey=${{inputs.cq_project_key}} 
           -Dsonar.host.url=${{inputs.cq_host_url}} 
           -Dsonar.login=${{inputs.cq_token}}
      shell: bash
    
    - name: Validate Gradle wrapper
      if: ${{ inputs.build_tool == 'gradle' }}
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      
    - name: Build with Gradle
      if: ${{ inputs.build_tool == 'gradle' }}
      run: ./gradlew build
      shell: bash
      
        
    
    
      ############ Test Ignore ##########
      
    - name: calling another composite action
      id: foo
      uses: gopinath-velayudhan-mns/shared_composite_repo/workflows/sample@main
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
