# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running Security Scans for project codes'
inputs:
  application_name:
    required: true
  build_tool:
    required: true
  jdk_version:
    required: false
  node_version: 
    required: false
  run_dependency_scan:
    required: true
  dependency_scan_token:
    required: false
  dependency_scan_arguments:
    required: false
  
  run_sast_scan:
    required: true
  sast_release_id:
    required: false
  sast_api_key:
    required: false
  sast_api_secret:
    required: false
  sast_scan_notes:
    required: false
  sast_scan_options:
    required: false
  application_src_path:
    required: false
  application_artifact_zip_path:
    required: false
  download_sast_scan_result:
    required: false
    default: false
    
  run_dast_scan:   
    required: false
    
  run_container_scan:
    required: false
  container_scan_user:
    required: false
  container_scan_password:
    required: false
  container_scan_url:
    required: false
  image_name:
    required: false
  image_tag:
    required: false
  registry_server:
    required: false
  registry_username:
    required: false
  registry_password:
    required: false
  
  json_results_file_name:
    required: false
  sarif_results_file_name:
    required: false
  
runs:
  using: "composite"
  steps:
  - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
    shell: bash
    
  - name: Install JAVA 
    uses: actions/setup-java@v2
    if: ${{inputs.jdk_version}}
    with:
      distribution: 'adopt' # See 'Supported distributions' for available options
      java-version: '${{inputs.jdk_version}}'   
   
  - name: Install Node
    if: ${{inputs.node_version}}
    uses: actions/setup-node@v3
    with:
      node-version: ${{inputs.node_version}}
      
      
##################  DEPENDENCY SCAN PROCESS - SNYK ############################    

  - run: echo  argument for run_dependency_scan = ${{inputs.run_dependency_scan}}
    shell: bash
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash   
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  - name: Message
    run: |
       echo #                                      Running Dependency SCAN                                            #
    shell: bash
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  
  - name: Snyk SCA Scanning
    uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/appsec/snyk@marketplace_upgrade_appsec
    with:      
      dependency_scan_token: ${{ inputs.dependency_scan_token }}
      dependency_scan_arguments: ${{ inputs.dependency_scan_arguments }}
      build_tool: ${{ inputs.build_tool }}
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  - name: Message
    run: |
       echo #                                      Finished Dependency SCAN                                            #
    shell: bash
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_dependency_scan == 'true' &&  inputs.dependency_scan_token }}
    
    
    
    
    
##################  CONTAINER SCAN PROCESS - PRISMA ############################

  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
  - name: Message
    run: |
       echo #                                      Running Container SCAN                                       #
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
  - name: Run Container Scan for Repostiory
    uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/appsec/prisma@marketplace_upgrade_appsec
    with: 
      container_scan_user: ${{ inputs.container_scan_user }}
      container_scan_password: ${{ inputs.container_scan_password }}
      container_scan_url: ${{ inputs.container_scan_url }}
      image_name: ${{inputs.image_name}}
      image_tag: ${{inputs.image_tag}}
      registry_server: ${{inputs.registry_server}}
      registry_username: ${{ inputs.registry_username }}
      registry_password: ${{ inputs.registry_password }}
      json_results_file_name: ${{ inputs.json_results_file_name }}
      sarif_results_file_name: ${{ inputs.sarif_results_file_name }}
    
    if: ${{ inputs.run_container_scan == 'true' }}  
    
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
  - name: Message
    run: |
       echo #                                      Finished Container SCAN                                       #
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_container_scan == 'true' }}
   
   
   
   

##################  SAST SCAN PROCESS - FOD ############################
  
  - run: echo  argument for run_sast_scan = ${{inputs.run_sast_scan}}
    shell: bash
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_sast_scan == 'true' }}
  - name: Message
    run: |
       echo #                                      Running SAST SCAN                                            #
    shell: bash
    if: ${{inputs.run_sast_scan == 'true' }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_sast_scan == 'true' }}
    
  - name: Fortify Scan Create source Zip upload to FOD for Scanning
    uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/appsec/fortify@marketplace_upgrade_appsec
    with:
      sast_release_id: ${{inputs.sast_release_id }}
      sast_api_key: ${{ inputs.sast_api_key}}
      sast_api_secret: ${{ inputs.sast_api_secret}}
      sast_scan_options: ${{ inputs.sast_scan_options }}
      sast_scan_notes: ${{inputs.sast_scan_notes}}
      application_name: ${{inputs.application_name}}
      application_src_path: ${{inputs.application_src_path}}
      application_artifact_zip_path: ${{inputs.application_artifact_zip_path}}
      download_sast_scan_result: ${{ inputs.download_sast_scan_result }}
    if: ${{inputs.run_sast_scan == 'true' }}
    
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash   
    if: ${{inputs.run_sast_scan == 'true' }}
  - name: Message
    run: |
       echo #                                      Finished SAST SCAN                                            #
    shell: bash
    if: ${{inputs.run_sast_scan == 'true' }}
  - name: Message
    run: |
       echo #===================================================================================================#
    shell: bash
    if: ${{inputs.run_sast_scan == 'true' }}
   
  

       
