# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  build_tool:
    required: true
    default: maven
  build_file_path:
    required: false
    default: .
  build_file_name:
    required: false
    
  settings_file_path:
    required: false
  settings_file_name:
    required: false
  build_arguments:
    required: false
  build_phases: 
    required: false
    
  artifact_repository_pat:
    required: false
    
  run_code_analysis:
    required: true
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments:
     required: false
 
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - name: prep
      run: |
         [ -f ./gradlew ] && chmod +x gradlew
      shell: bash   
      env:
        BUILD_FILE: ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }}
      
    - name: Build with Gradle
      run: ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} ${{ inputs.build_phases }} ${{inputs.build_arguments}}
      shell: bash
      
    - name: Code Quality Analysis
      if: ${{ inputs.run_code_analysis == 'true' }}  
      run: ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} sonarqube
           -Dsonar.projectKey=${{inputs.cq_project_key}} 
           -Dsonar.host.url=${{inputs.cq_host_url}} 
           -Dsonar.login=${{inputs.cq_token}} ${{inputs.build_arguments}} ${{ inputs.cq_scan_arguments }}
      shell: bash  
      

#     - name: Validate Gradle wrapper
#       if: ${{ inputs.build_tool == 'gradle' }}
#       uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
