# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - new-feature
    - title: Bug Fixes
      labels:
        - bug-fix
    - title: Enhancement
      labels:
        - additional-field
        - enhancement
    - title: Updating Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
