site_name: 'Cloud DevSecOps Pipeline - Reusable Composite Actions'
site_description: 'Cloud DevSecOps Reusable Composite Actions Library to help product teams be up and running faster with M&S standard integrations'

plugins:
  - techdocs-core

nav:
   - Overview: index.md
