# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running SNYK Security Scans for project codes'

inputs:
  project_name:
    required: false
  dependency_scan_token:
    required: false
  dependency_scan_arguments:
    required: false
  build_tool:   
    required: false
    
    
runs:
  using: "composite"
  steps:
  - name: Snyk SCA Scanning
    uses: snyk/actions/maven@0.3.0
    env:
       SNYK_TOKEN: ${{ inputs.dependency_scan_token }}
    with:
       args: --sarif-file-output=snyk.sarif -- ${{inputs.dependency_scan_arguments}} || true
    
#   - name: Upload result to GitHub Code Scanning
#     uses: github/codeql-action/upload-sarif@v1
#     with:
#        sarif_file: snyk.sarif
       
  - name: Snyk SCA Scanning
    uses: snyk/actions@0.3.0
    env:
       SNYK_TOKEN: ${{ inputs.dependency_scan_token }}
    with:
       command: monitor      
#     run: |
#       echo SNYK token is provided running SNYK scan for the project
#       echo "----------Download Latest Snyk CLI-----------"
#       curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.683.0/snyk-linux"
#       chmod +x snyk
#       ls -lrt
#       echo ./snyk auth ${{inputs.dependency_scan_token}}
#       ./snyk auth ${{inputs.dependency_scan_token}}
#       ./snyk test --all-projects -- ${{inputs.dependency_scan_arguments}}  || true
#       ./snyk monitor --all-projects -- ${{inputs.dependency_scan_arguments}} || true
#     shell: bash 
    
         
