# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running SNYK Security Scans for project codes'

inputs:
  application_name:
    required: false
  dependency_scan_token:
    required: false
  dependency_scan_arguments:
    required: false
  build_tool:   
    required: false
    
    
runs:
  using: "composite"
  steps:
  
  - uses: snyk/actions/setup@master
  - name: Snyk monitor
    continue-on--error: true
    run: snyk test --all-projects ${{inputs.dependency_scan_arguments}}
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      
  - name: Snyk Continuous Monitor
    run: snyk monitor
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      
      
      
      
      
#   - name: Snyc scan for maven and gradle     
#     run: |
#       echo SNYK token is provided running SNYK scan for the project
#       echo "----------Download Latest Snyk CLI-----------"
#       curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.950.0/snyk-linux"
#       chmod +x snyk
#       ./snyk auth ${{inputs.dependency_scan_token}}
#       ./snyk test --all-projects ${{inputs.dependency_scan_arguments}}  || echo "snyk scan completed"
#       ./snyk monitor --all-projects ${{inputs.dependency_scan_arguments}}  || echo "snyk monitor enabling completed"
#     shell: bash 
    if: ${{ inputs.build_tool != 'npm' || inputs.build_tool != 'yarn' }}
    

#   ############ SNYK using MarketPlace Actions   ##################
#   - name: Snyk SCA Scanning for java scripts
#     if: ${{ inputs.build_tool == 'npm' || inputs.build_tool == 'yarn' }}
#     uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/appsec/snyk/nodejs-snyk@latest
#     with:      
#       dependency_scan_token: ${{ inputs.dependency_scan_token }}
#       dependency_scan_arguments: ${{ inputs.dependency_scan_arguments }}
#       build_tool: ${{ inputs.build_tool }}
      
      
      
      
#     uses: snyk/actions@0.3.0
#     env:
#        SNYK_TOKEN: ${{ inputs.dependency_scan_token }}
#     with:
#        args: --sarif-file-output=snyk.sarif 
       
#   - name: Snyk SCA Scanning for Java scripts
#     if: ${{ inputs.build_tool == 'npm' || inputs.build_tool == 'yarn' }}
#     uses: snyk/actions@0.3.0
#     env:
#        SNYK_TOKEN: ${{ inputs.dependency_scan_token }}
#     with:
#        command: monitor
    
#   - name: Upload result to GitHub Code Scanning
#     uses: github/codeql-action/upload-sarif@v1
#     with:
#        sarif_file: snyk.sarif     
