# push_image.yml
name: 'Push docker images'
description: 'Pushing Docker image to Container Registry'
inputs:
  
  cr_imagename:
    required: true
  cr_imagetag:
    required: true
  cr_dockerfile_name:
    required: true
  cr_dockerfile_path:
    required: true
  cr_servername:
    required: true
  cr_subscription:
    required: true
  cr_tenant:
    required: true
  cr_username:
    required: false
  cr_password:
    required: flase
   
    
runs:
  using: "composite"
  steps:
    - run: ls -lart
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash
    - run: docker images
      shell: bash
      
########### Login and Push image to Azure Container Registry ##############

#     - uses: Azure/docker-login@v1
#       with:
#         username: ${{inputs.cr_username}}
#         password: ${{inputs.cr_password}}
#         login-server: ${{inputs.cr_servername}}  
#     - run: |
#         echo docker tag ${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }} ${{ inputs.cr_servername }}/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}
#         docker tag ${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }} ${{ inputs.cr_servername }}/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}
#         echo runningg command: docker push ${{ inputs.cr_servername }}/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}  
#         docker push ${{ inputs.cr_servername }}/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}
#       shell: bash





#########  Switching over to Github Packages ##########
    - name: Log in to the GITHUB Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Execute build 
      run: |
        echo =================  Pushing to Github Packages ======================
        docker images
        docker tag  ${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }} ghcr.io/digitalinnovation/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}
        docker images
        docker push ghcr.io/digitalinnovation/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }}
      shell: bash









#     - name: Log in with Azure
#       uses: azure/login@v1
#       with:
#         creds: '${{ inputs.AZURE_CREDENTIALS }}'

#     - name: Build and Push Docker to ACR       
#       run: |
#         az login --service-principal --username ${{inputs.cr_username}} --password ${{inputs.cr_password}} --tenant ${{inputs.cr_tenant}}
#         #az acr login -n ${{ inputs.cr_servername }} --username ${{inputs.cr_username}} --password ${{inputs.cr_password}} --subscription ${{ inputs.cr_subscription}}
#         docker images
#         az acr build --registry ${{ inputs.cr_servername }} -t ${{ inputs.cr_servername }}/${{inputs.cr_imagename}}:${{ inputs.cr_imagetag }} --file ./${{inputs.cr_dockerfile_path}}${{inputs.cr_dockerfile_name}} .
#       shell: bash


