name: 'Code Quality Scan'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  build_tool:
    required: true
  build_tool_version:
    required: false
  application_name:
    required: true
  build_file_path:
    required: false
    default: .
  build_file_name:
    required: false
  settings_file_path:
    required: false
  settings_file_name:
    required: false
  jdk_version:
    required: false
  node_version: 
    required: false
    
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments:
    required: false
  cq_project_name: 
    required: false  
  
  
    
 
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Code Scan
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash
      
    - name: ========== Run Code Quality Scan for Maven project ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/codequality/maven-cq@latest
      with:
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        settings_file_path: ${{ inputs.settings_file_path }}
        settings_file_name: ${{ inputs.settings_file_name }}
        jdk_version: ${{ inputs.jdk_version }}
        cq_host_url: ${{ inputs.cq_host_url }} 
        cq_project_key: ${{ inputs.cq_project_key }} 
        cq_project_name: ${{ inputs.cq_project_name }}
        cq_token: ${{ inputs.cq_token }}
        cq_scan_arguments: ${{ inputs.cq_scan_arguments }}
        
      if: ${{ ( inputs.build_tool == 'maven' || inputs.build_tool == 'mvn' ) }}
    
    - name: ========== Run Code Quality Scan for Maven project ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/codequality/gradle-cq@latest
      with:
        build_file_path: ${{ inputs.build_file_path }}
        build_file_name: ${{ inputs.build_file_name }}
        jdk_version: ${{ inputs.jdk_version }}
        cq_host_url: ${{ inputs.cq_host_url }} 
        cq_project_key: ${{ inputs.cq_project_key }}
        cq_project_name: ${{ inputs.cq_project_name }}
        cq_token: ${{ inputs.cq_token }}
        cq_scan_arguments: ${{ inputs.cq_scan_arguments }}
        
      if: ${{ ( inputs.build_tool == 'gradle' || inputs.build_tool == 'gradlew' ) }}
    
    
    
