# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  maven_version:
    required: false
  jdk_version:
    required: false
  build_file_path:
    required: false
  build_file_name:
    required: false
  settings_file_path:
    required: false
  settings_file_name:
    required: false
  build_arguments:
    required: false
  build_phases: 
    required: false
  build_and_push_container_image:
    required: false
  artifact_repository_pat:
    required: false
    
  run_code_quality_analysis:
    required: true
  cq_project_key:
    required: false
  cq_project_name:
    required: false  
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments: 
    required: false
 
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run: ls -lart
      shell: bash
      
    - name: install java version requested
      uses: actions/setup-java@v2
      with:
        java-version: ${{inputs.jdk_version}}
        distribution: 'adopt'
      if: ${{inputs.jdk_version}}
      
    - name: Maven Build and install Artifacts
      if: ${{ contains( inputs.build_phases,'install') || contains(  inputs.build_phases , 'package') }}
      run: |
        mvn clean install ${{inputs.build_arguments}} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
      shell: bash  
    
    - name: Unit_Test
      if: ${{ contains( inputs.build_phases , 'test' ) }} 
      run : | 
        echo Running Unit Test - ${{ inputs.build_phases }}
        mvn test ${{inputs.build_arguments}} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }}
        echo 'Test Phase - completed'
      shell: bash
      
    - name: Publish built artifact to Artifact repository
      if: ${{ contains( inputs.build_phases , 'deploy' ) && inputs.settings_file_name }}   
      run : |
        echo Executing Phase Deploy - ${{ inputs.build_phases }}
        mvn deploy -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }} -f ./${{ inputs.build_file_path }}/${{ inputs.build_file_name }} ${{inputs.build_arguments}}
      shell: bash  
      
    - name: Code Quality Analysis
      if: ${{ inputs.run_code_quality_analysis == 'true' && inputs.cq_project_key }}  
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar
           -Dsonar.projectKey=${{inputs.cq_project_key}} 
           -Dsonar.projectName=${{inputs.cq_project_name}}
           -Dsonar.host.url=${{inputs.cq_host_url}} 
           -Dsonar.login=${{inputs.cq_token}} ${{inputs.build_arguments}} ${{ inputs.cq_scan_arguments }}
      shell: bash
    
    - name: Code Quality Analysis
      if: ${{ inputs.run_code_quality_analysis == 'true' && ( !inputs.cq_project_key || inputs.cq_project_key == '' ) }}  
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar
           -Dsonar.projectName=${{inputs.cq_project_name}}
           -Dsonar.host.url=${{inputs.cq_host_url}} 
           -Dsonar.login=${{inputs.cq_token}} ${{inputs.build_arguments}} ${{ inputs.cq_scan_arguments }}
      shell: bash  
    
