name: 'New Relic Deployment Marker actions'
description: 'New Relic Deployment Marker actions'

inputs:
  newRelic_key: 
  newRelic_accountId: 
  newRelic_applicationId: 
  newRelic_user:
  git_commit_id: 
  comment:
  
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Create New Relic deployment marker
      uses: newrelic/deployment-marker-action@v1
      with:
        apiKey: ${{inputs.newRelic_key}}
        accountId: ${{inputs.newRelic_accountId}}
        applicationId: ${{inputs.newRelic_applicationId}}
        revision: ${{inputs.git_commit_id}}
        description: ${{inputs.comment}}
        user: ${{inputs.newRelic_user}}
