name: 'Build Nodejs project'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  application_name:
    required: true
  build_environment:
    required: false
    default: 'nonprod'
    
  build_file_path:
    required: false
  build_file_name:
    required: false
  build_tool_version:
    required: false
  build_and_push_container_image:
    required: false
    
  run_code_quality_analysis:
    required: false
  yarn_code_quality_analysis_script:
    required: false
    
  run_typecheck_validation:
    required: false
  yarn_typecheck_validation_script:
    required: false
    
  run_schema_validation:
    required: false
  yarn_schema_validation_script:
    required: false
    
  run_unit_test:
    required: false
  yarn_unit_test_script:
    required: false
    
    
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments: 
    required: false
 
    
runs:
  using: "composite"
  steps:
    
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - name: Checkout
      uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2.1.0
    - name: Setup NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.build_tool_version }}
    - name: Install JS dependencies
      run: yarn install
      shell: bash
    - name: Build
      run: yarn build
      shell: bash
         
    - name: Run ESLint
      if: ${{ inputs.run_code_quality_analysis == 'true' }}
      run: yarn eslint
      shell: bash
    - name: Run ESLint
      if: ${{ inputs.run_code_quality_analysis == 'true' && inputs.yarn_code_quality_analysis_script != null }}
      run: yarn ${{ inputs.yarn_code_quality_analysis_script }}
      shell: bash  
      
    - name: TypeScript Type Checking
      if: ${{ inputs.run_typecheck_validation == 'true' }}
      run: yarn typecheck
      shell: bash
    - name: TypeScript Type Checking
      if: ${{ inputs.run_typecheck_validation == 'true' && inputs.yarn_typecheck_validation_script != null }}
      run: yarn ${{ inputs.yarn_typecheck_validation_script }}
      shell: bash 
      
    - name: Run unit test
      if: ${{ inputs.run_unit_test == 'true' }}
      run: yarn test --ci --coverage --coverageReporters="json-summary"
      shell: bash
    - name: Run unit test
      if: ${{ inputs.run_unit_test == 'true' && inputs.yarn_unit_test_script != null }}
      run: yarn ${{ inputs.yarn_unit_test_script }}
      shell: bash  
      
    - name: Run GraphQL Inspector
      if: ${{ inputs.run_schema_validation == 'true' }}
      run: yarn diff-schema   
      shell: bash
    - name: Run GraphQL Inspector
      if: ${{ inputs.run_schema_validation == 'true' && inputs.yarn_schema_validation_script != null }}
      run: yarn ${{ inputs.yarn_schema_validation_script }}   
      shell: bash  
      
      
      
      
    - name: Tag the app with version
      run: echo ${{ github.sha }}>./version
      shell: bash
    - name: Zip Web App package
      run: zip -r "./${{ inputs.application_name }}.zip" . --exclude @.zipignore --exclude .zipignore
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact-${{ github.sha }}
        path: |
          ./${{ inputs.application_name }}.zip
          dist
          version  
