name: 'Build Nodejs project'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  application_name:
    required: true
  build_file_path:
    required: false
  build_file_name:
    required: false
  build_tool_version:
    required: false
  build_arguments:
    required: false
  build_phases: 
    required: false
  node_version:
    required: false
  build_and_push_container_image:
    required: false
  run_code_quality_analysis:
    required: true
  cq_project_key:
    required: false
  cq_host_url:
    required: false
  cq_token:
    required: false
  cq_scan_arguments: 
    required: false
 
    
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
#       - name: Cache node modules
#         uses: actions/cache@v2
#         env:
#           cache-name: cache-node-modules
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
            
      - name: Setup NodeJs 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
         
#       - name: Npm Audit
#         run: npm audit --production --audit-level critical
#         shell: bash
      
      - name: Npm install
        run: npm install
        shell: bash
        if: ${{ contains( inputs.build_phases,'install')
        
      - name: Npm ci
        run: npm ci
        shell: bash
        if: ${{ contains( inputs.build_phases,'ci')  
        
      - name: Lint
        run: npm run lint
        shell: bash
        if: ${{ contains( inputs.build_phases,'lint') 
        
      - name: Formatting Check
        run: npm run format:check
        shell: bash
        
      - name: Unit tests
        run: npm run test:coverage
        shell: bash
        
      - name: Typescript Errors
        run: npm run build:ts
        shell: bash
      
      - name: Npm Publish
        run: npm publish
        shell: bash
        if: ${{ contains( inputs.build_phases,'publish')
