# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running Security Scans for project codes'
inputs:
  run_container_scan:
    required: false
  container_scan_user:
    required: false
  container_scan_password:
    required: false
  container_scan_url:
    required: false
  docker_image_name:
    required: false
  docker_image_tag:
    required: false
  docker_repo:
    required: false
    
  
  
runs:
  using: "composite"
  steps:
    - name: Run Prisma Scan for Repository
      run: |
        curl --user ${{ inputs.container_scan_user }}:${{ inputs.container_scan_password }} --output ./twistcli ${{ inputs.container_scan_url }}/api/v1/util/twistcli
        chmod a+x ./twistcli     
      shell: bash
    - name: Scan the image using Prisma Cloud
      run: |
        #./twistcli images scan --address ${{ inputs.container_scan_url }} --user ${{ inputs.container_scan_user }} --password ${{ inputs.container_scan_password }} --details ${{inputs.docker_image_name}}:${{inputs.docker_image_tag}}
        ./twistcli images scan --address ${{ inputs.container_scan_url }} --user ${{ inputs.container_scan_user }} --password ${{ inputs.container_scan_password }} --containerized --details ${{inputs.docker_repo}}${{inputs.docker_image_name}}:${{inputs.docker_image_tag}}
      shell: bash
