name: 'DevSecOps Application Security Actions'
description: 'Running Fority Security Scans for project codes'

inputs:
  
  environment:
    required: false
    default: dev    
  application_release_name:
    required: false
  webapp_name:
    required: true
  resource_group:
    required: false
  source_path:
    required: false
  azure_profile:
    required: false
  
  
runs:
  using: "composite"
  steps:
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{inputs.webapp_name}}
        publish-profile: ${{ inputs.azure_profile }}
        package: ${{inputs.source_path}}
        
#   - name: Deploy to Azure Web Apps
#     uses: azure/CLI@v1
#     id: webapp
#     with:
#         inlineScript: |
#           RETRY=5;
#           SLEEP=5;
#           COUNT=0;
#           CMD="az webapp deployment source config-zip \
#             --resource-group ${{ inputs.resource_group }} \
#             --name ${{ inputs.application_release_name }} \
#             --src ${{ inputs.source_path }} --timeout 360";
#           until [ "$COUNT" -ge $RETRY ]
#           do
#             $CMD && break;
#             COUNT=$((COUNT+1));
#             sleep $SLEEP;
#           done
#           if test $COUNT -eq $RETRY
#           then
#             echo "Deployment was unsuccesful :(";
#             exit 127;
#           fi
