# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running Fority Security Scans for project codes'

inputs:
  sast_release_id:
    required: true
  sast_api_key:
    required: true
  sast_api_secret:
    required: true
  sast_scan_notes:
    required: false 
  project_name:
    required: true
  project_src_path:
    required: false
  project_artifact_zip_path:
    required: false
  
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing FOTIFY Scan
      shell: bash
    - name: Fortify Scan Create source Zip upload to FOD for Scanning
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download fortify executable and run scan 
    #- name: Download Fortify on Demand Universal CI Tool
    #  uses: fortify/gha-setup-fod-uploader@v1.1.1
      run: |
         sudo wget -c https://github.com/fod-dev/fod-uploader-java/releases/download/v5.2.1/FodUpload.jar  
         if [[ ! -z "${ARTIFACT_ZIP_PATH}" ]]
           then
             java -jar FodUpload.jar -ac ${{ inputs.sast_api_key }} ${{ inputs.sast_api_secret }} -rid ${{ inputs.sast_release_id }} -purl ${{ env.SAST_PORTAL_URL }} -apiurl ${{ env.SAST_API_URL }} -z ${{inputs.project_artifact_zip_path}} ${{ env.SAST_OPTIONS }}  -n 'notes:${{ inputs.sast_scan_notes}}'  
           else
              sudo apt install zip
              zip -r ${{inputs.project_name}}_fortify.zip .
              java -jar FodUpload.jar -ac ${{ inputs.sast_api_key }} ${{ inputs.sast_api_secret }} -rid ${{ inputs.sast_release_id }} -purl ${{ env.SAST_PORTAL_URL }} -apiurl ${{ env.SAST_API_URL }} -z ${{inputs.project_name}}_fortify.zip ${{ env.SAST_OPTIONS }}  -n 'notes:${{ inputs.sast_scan_notes}}'  
          fi
      shell: bash
      env:
        SAST_PORTAL_URL: https://emea.fortify.com/
        SAST_API_URL: https://api.emea.fortify.com/
        SAST_OPTIONS: '-ep 2 -a 2 -rp 0 -pp 1 -apf -I 1'
        ARTIFACT_ZIP_PATH: ${{inputs.project_artifact_zip_path}}
  ###=====================================================      
        
#         - uses: actions/download-artifact@v2
#         with:
#           name: ${{ github.sha }}
#       - name: Download Fortify on Demand Universal CI Tool
#         uses: fortify/gha-setup-fod-uploader@v1.1.1
#       - name: Perform SAST Scan
#         run: java -jar $FOD_UPLOAD_JAR -z $PACKAGE_LOCATION -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -ac "$FOD_APIKEY" "$FOD_APISECRET" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
#         env:
#           FOD_APIKEY: ${{ secrets.FOD_API_KEY }}
#           FOD_APISECRET: ${{ secrets.FOD_API_SECRET }}
#           FOD_RELEASE_ID: 68974
#           FOD_URL: https://emea.fortify.com/
#           FOD_API_URL: https://api.emea.fortify.com
#           FOD_UPLOADER_OPTS: "-ep 1 -rp 0 -pp 1 -apf -I 1"
#           FOD_UPLOADER_NOTES: "Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
#       - name: Download Results
#         uses: fortify/gha-fod-generate-sarif@v1.1.1
#         with:
#           base-url: https://emea.fortify.com/
#           client-id: ${{ secrets.FOD_APIKEY }}
#           client-secret: ${{ secrets.FOD_API_SECRET }}
#           release-id: 68974
#           output: ./sarif/output.sarif
  
        
        
      
            
